name: Fly Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only  --build-secret API_URL="${{ secrets.API_URL }}" --build-secret API_KEY="${{ secrets.API_KEY }}" --build-secret ADMIN_LOGIN="${{ secrets.ADMIN_LOGIN }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
