name: Fly Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only \
            --build-secret API_URL="${{ secrets.API_URL }}" \
            --build-secret API_KEY="${{ secrets.API_KEY }}" \
            --build-secret ADMIN_LOGIN="${{ secrets.ADMIN_LOGIN }}" \
            --build-secret AZURE_STORAGE_ACCOUNT_NAME="${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            --build-secret AZURE_STORAGE_ACCOUNT_KEY="${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
            --build-secret AUTH_SECRET="${{ secrets.AUTH_SECRET }}" \
            --build-secret AUTH_GOOGLE_ID="${{ secrets.AUTH_GOOGLE_ID }}" \
            --build-secret AUTH_GOOGLE_SECRET="${{ secrets.AUTH_GOOGLE_SECRET }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
